config/routes.rb
Rails.application.routes.draw do

root 'sessions#new'
  resources :issues
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
		belongs_to :usuario, optional: true
	    validates :Title,:Type , :Priority , presence: true
	    
#HOLA
	
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :issues
  validates :email, presence: true, uniqueness: true,format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user  
   	 def current_user
       	if session[:user_id]
       	@current_user ||= User.find(session[:user_id])
      	 else
      	@current_user = nil
     	 end
    
	 end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:Title, :Description, :Type, :Priority, :Status, :Asignee, :Creator, :Created, :Updated, :Vote)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to issues_url , notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :Description %>
  </div>
 

  <div class="field">
    <%= form.label :Type %>
    <%= form.select :Type,["bug","enhancement","proposal","task"],selected:"bug" %>
  </div>

  <div class="field">
    <%= form.label :Priority %>
    <%= form.select :Priority,["trivial","minor","major","critical","blocker"],selected:"major" %>
  </div>



  <div class="field">
    <%= form.label :Asignee %>
    <%= form.collection_select :Asignee, User.all ,:name,:name,{:include_blank => 'No assigned user'} %>
  </div>

  

  <div class="field">
    <%= form.label :Created %>
    <%= form.date_select :Created %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/_form1.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :Description %>
  </div>
 

  <div class="field">
    <%= form.label :Type %>
    <%= form.select :Type,["bug","enhancement","proposal","task"],selected:"bug" %>
  </div>

  <div class="field">
    <%= form.label :Priority %>
    <%= form.select :Priority,["trivial","minor","major","critical","blocker"],selected:"major" %>
  </div>



  <div class="field">
    <%= form.label :Asignee %>
    <%= form.collection_select :Asignee, User.all ,:name,:name,{:include_blank => 'No assigned user'} %>
  </div>

  

  <div class="field">
    <%= form.label :Updated %>
    <%= form.date_select :Updated %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form1', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Type</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Asignee</th>
      <th>Creator</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.order("title ASC").each do |issue| %>
      <tr>
        <td><%= issue.Title %></td>
        <td><%= issue.Description %></td>
        <td><%= issue.Type %></td>
        <td><%= issue.Priority %></td>
        <td><%= issue.Status %></td>
        <td><%= issue.Asignee %></td>
        <td><%= issue.Creator %></td>
        <td><%= issue.Created %></td>
        <td><%= issue.Updated %></td>
        <td><%= issue.Vote %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.Title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.Description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @issue.Type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @issue.Priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.Status %>
</p>

<p>
  <strong>Asignee:</strong>
  <%= @issue.Asignee %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @issue.Creator %>
</p>

<p>
  <strong>Created:</strong>
  <%= @issue.Created %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @issue.Updated %>
</p>

<p>
  <strong>Vote:</strong>
  <%= @issue.Vote %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IssueTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', new_session_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Login', new_session_path %>